app:
  name: feuer
  version: 0.0.1

system:
  port: 8848

on-off:
  sync-db: true

mysql:
  ip: 120.25.194.74
  port: 30306
  username: root
  password: 123456!
  database: feuer

redis:
  ip: 120.25.194.74
  port: 31379
  db: 0
  password: ''

jwt:
  signing-key: 'youcannotseeme'
  expires-time: 604800
  buffer-time: 86400
  issuer: 'ganwei'